import React,{useState,useMemo,useRef,useLayoutEffect,useEffect} from 'react';
import {defaults,calculate,audit} from '../lib/affinity.js';
import '../styles/affinity.css';
import {toDisplay,fromDisplay,unit as displayUnit} from '../lib/affinity-units.js';
const fmt=v=>v===null?'Unavailable':Number(v.toPrecision(6)).toLocaleString('en-US',{maximumSignificantDigits:6});
const names={q:'Baseline flow Q₁',h:'Baseline head H₁',p:'Baseline shaft power P₁',n1:'Baseline speed N₁',n2:'Proposed speed N₂',d1:'Baseline diameter D₁',d2:'Proposed diameter D₂',eq:'Flow exponent',eh:'Head / pressure exponent',ep:'Power exponent',shutoff:'Baseline shutoff head',static:'System static head',bep:'Baseline BEP flow',motor:'Motor efficiency',drive:'VFD efficiency',hours:'Annual operating hours',rate:'Electricity cost',npshr:'Baseline NPSHr',npsha:'Proposed NPSHa'};
function Curve({i,r,svgRef,ip}) {
 const display=(k,v)=>toDisplay(k,v,i.equipment,ip), unit=k=>displayUnit(k,i.equipment,ip);
 const xmax=Math.max(i.q,r.q,r.op||0)*1.65,ymax=Math.max(i.shutoff,i.shutoff*r.s[1],r.oh||0)*1.14;
 const x=q=>66+q/xmax*714,y=h=>348-h/ymax*290;
 const path=fn=>Array.from({length:181},(_,j)=>{const q=xmax*j/180;return `${j?'L':'M'}${x(q)},${y(fn(q))}`;}).join(' ');
 return <svg ref={svgRef} className="af-chart" viewBox="0 0 850 410" role="img" aria-labelledby="af-chart-title af-chart-desc">
  <title id="af-chart-title">Pump/fan curve and system curve</title><desc id="af-chart-desc">Quadratic model. {r.op===null?'No positive operating point.':`Operating flow ${fmt(display('q',r.op))} ${unit('q')} at ${fmt(display('h',r.oh))} ${unit('h')}.`}</desc>
  <defs><clipPath id="af-clip"><rect x="66" y="58" width="714" height="290"/></clipPath></defs>
  {Array.from({length:6},(_,j)=><g key={j}><path d={`M${66+j*142.8} 58V348M66 ${58+j*58}H780`} className="af-gridline"/><text x={66+j*142.8} y="371" textAnchor="middle">{fmt(display('q',xmax*j/5))}</text><text x="54" y={352-j*58} textAnchor="end">{fmt(display('h',ymax*j/5))}</text></g>)}
  <g clipPath="url(#af-clip)" fill="none"><path d={path(q=>i.shutoff-r.a*q*q)} stroke="#829bb4" strokeWidth="2" strokeDasharray="7 6"/><path d={path(r.system)} stroke="#e9ac52" strokeWidth="2.5"/><path d={path(r.pump)} stroke="#49c9d5" strokeWidth="3" className="af-glow"/>
  {r.op!==null&&<g><path d={`M66 ${y(r.oh)}H${x(r.op)}V348`} stroke="#a4b4c5" strokeDasharray="3 6"/><circle cx={x(r.op)} cy={y(r.oh)} r="13" fill="#60d6ad" fillOpacity=".18"/><circle cx={x(r.op)} cy={y(r.oh)} r="6" fill="#8aefc2" stroke="#fff" strokeWidth="2"/></g>}</g>
  <path d="M66 58V348H780" fill="none" className="af-axis"/><text x="66" y="29">{`${i.equipment==='fan'?'PRESSURE':'HEAD'} / ${unit('h')}`} </text><text x="423" y="401" textAnchor="middle">FLOW / {unit('q')}</text><text x="780" y="29" textAnchor="end">QUADRATIC PERFORMANCE MODEL</text>
 </svg>;
}
export default function AffinityCalculator(){
 const [ip,setIp]=useState(false);
 const [i,setI]=useState(defaults),[light,setLight]=useState(false),[paused,setPaused]=useState(false),[verified,setVerified]=useState(false),[pdfState,setPDF]=useState(''),root=useRef(null),svg=useRef(null);
 const result=useMemo(()=>{try{const r=calculate(i);if(audit(i,r)<8)throw Error('Calculation could not be verified. Check inputs and retry.');return {r};}catch(e){return {error:e.message};}},[i]);
 const r=result.r;
 const display=(k,v)=>toDisplay(k,v,i.equipment,ip);
 const unit=k=>displayUnit(k,i.equipment,ip);
 const value=(k,v)=>`${fmt(display(k,v))} ${unit(k)}`;
 useEffect(()=>{try{setLight(localStorage.getItem('affinity-theme')==='light');}catch{}},[]);
 // The output group stays hidden until its rendered numeric text is checked.
 useLayoutEffect(()=>{setVerified(false);if(!r)return;const nodes=[...root.current.querySelectorAll('[data-affinity-value]')];const ok=nodes.length===3&&nodes.every((n,j)=>Math.abs(Number(n.textContent.replaceAll(',',''))-[display('q',r.q),display('h',r.h),display('p',r.p)][j])<=Math.max(0.00001,Math.abs([display('q',r.q),display('h',r.h),display('p',r.p)][j])*0.00001));setVerified(ok&&audit(i,r)>=8);},[r,i,ip]);
 const update=(key,value)=>{setVerified(false);setI(old=>({...old,[key]:value}));};
 const label=k=>i.equipment==='fan'?names[k].replace('head H₁','pressure Δp₁').replace('head','pressure'):names[k];
 const field=k=><label className="af-field" key={k} htmlFor={`af-${k}`}><span>{label(k)} <small>{unit(k)}</small></span><input id={`af-${k}`} type="number" step="any" value={i[k]===''?'':Number(display(k,i[k]).toPrecision(12))} min={['n2','static','hours','rate','npshr','npsha'].includes(k)?0:0.000001} max={['motor','drive'].includes(k)?100:k==='hours'?8784:undefined} onChange={e=>update(k,e.target.value===''?'':fromDisplay(k,Number(e.target.value),i.equipment,ip))}/></label>;
 const switchEquipment=equipment=>{setVerified(false);setI({...defaults,equipment,...(equipment==='fan'?{q:10000,h:500,shutoff:700,bep:10000,p:3,npshr:0,npsha:0}:{})});};
 async function exportPDF(){
  if(!verified||!r||pdfState==='Preparing report…')return;const chartSnapshot=svg.current.cloneNode(true);setPDF('Preparing report…');
  try{const {jsPDF}=await import('jspdf');const doc=new jsPDF({compress:true});let y=0;
   const header=(title)=>{doc.setFillColor(9,29,45);doc.rect(0,0,210,35,'F');doc.setTextColor(255);doc.setFontSize(10);doc.text('TILAK BHUSAL  /  ENGINEERING TOOLS',15,13);doc.setFontSize(18);doc.text(title,15,25);doc.setTextColor(25,45,60);y=47;};
   const line=(text)=>{doc.setFontSize(9);const lines=doc.splitTextToSize(text,178);if(y+lines.length*4.5>275){doc.addPage();header('Engineering analysis / continued');}doc.text(lines,16,y);y+=lines.length*4.5+3;};
   const table=(title,rows)=>{line(title);for(const [a,b] of rows){if(y>266){doc.addPage();header('Engineering analysis / continued');}doc.setFillColor(240,245,247);doc.rect(15,y-4,180,8,'F');doc.setFontSize(9);doc.text(a,18,y+1);doc.text(String(b),192,y+1,{align:'right'});y+=9;}y+=5;};
   header('Pump & Fan Affinity Laws Report');line(`Generated ${new Date().toISOString()} | ${ip?'Imperial':'SI'} | Model v1.1 | tilakbhusal.com`);
   table('01 / INPUTS',Object.keys(names).filter(k=>!(['npshr','npsha'].includes(k)&&i.equipment==='fan')).map(k=>[label(k).replaceAll('₁','1').replaceAll('₂','2').replace('Δp','pressure'),`${fmt(display(k,i[k]))} ${unit(k).replace('³','3')}`]));
   line(`Equipment: ${i.equipment}; scaling: ${i.mode}; advanced mode: ${i.advanced?'enabled':'disabled'}; active exponents Q/H/P: ${r.e.join(' / ')}.`);
   doc.addPage();header('Performance & energy analysis');
   table('02 / AFFINITY PREDICTIONS AT HOMOLOGOUS POINT',[['Flow Q2',value('q',r.q)],['Head / pressure H2',value('h',r.h)],['Shaft power P2',value('p',r.p)]]);
   table('03 / MODELED SYSTEM OPERATING POINT',[['Operating flow',value('q',r.op)],['Operating head / pressure',value('h',r.oh)],['Estimated operating shaft power',value('p',r.opPower)]]);
   table('04 / ANNUAL ELECTRICAL COST ANALYSIS',[['Baseline electrical input',`${fmt(r.baseKW)} kW`],['Proposed electrical input',`${fmt(r.newKW)} kW`],['Annual energy savings',`${fmt(r.kwh)} kWh`],['Estimated annual savings',r.savings===null?'Unavailable':`USD ${fmt(r.savings)}`]]);
   line('Savings use the modeled operating point, constant motor efficiency, and constant local hydraulic efficiency anchored to the scaled baseline shaft power. VFD efficiency applies only to speed mode. One operating condition is assumed for all entered hours; no demand charges or capital costs.');
   doc.addPage();header('Performance plot & assumptions');
   const clone=chartSnapshot;clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','1700');clone.setAttribute('height','820');clone.querySelectorAll('text').forEach(n=>{n.setAttribute('fill','#253d52');n.setAttribute('font-size','11');n.setAttribute('font-family','Arial');});clone.querySelectorAll('.af-gridline').forEach(n=>n.setAttribute('stroke','#d6e0e8'));clone.querySelectorAll('.af-axis').forEach(n=>n.setAttribute('stroke','#60758a'));
   const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=1700;canvas.height=820;const c=canvas.getContext('2d');c.fillStyle='white';c.fillRect(0,0,1700,820);c.drawImage(img,0,0);doc.addImage(canvas.toDataURL('image/png'),'PNG',12,y,186,90);}finally{URL.revokeObjectURL(url);}y+=96;
   line('Dashed: baseline performance. Cyan: proposed performance. Amber: system curve. Green marker: modeled intersection.');
   line('Model: Hbase(Q) = Hshutoff - a Q^2; Hsystem(Q) = Hstatic + K Q^2. Both pass through the entered baseline duty. Affinity scaling maps each performance-curve point; its intersection with the unchanged system is solved separately.');
   line('Imperial conventions: US gallons, international feet/inches, mechanical horsepower, and conventional inches of water (249.08891 Pa). Electrical inputs remain kW and energy remains kWh in both displays.');
   line('Constant fluid density and similar operation assumed. Speed exponents 1/2/3; same-casing pump trim 1/2/3 (approximate); geometric diameter scaling 3/2/5. Custom exponents are empirical. Curves are illustrative, not measured manufacturer curves.');
   line('NPSHr speed scaling is an approximate screen at homologous points only. NPSHa is user-supplied for the proposed condition. Actual cavitation margin, efficiency and fan stall require manufacturer data.');
   for(const w of r.warnings)line(`WARNING: ${w}`);
   line('References: Wilo, Affinity Laws Made Simple; Hydraulic Institute, Pump FAQs; AMCA, Fan Science and Engineering: Fan Affinity Laws.');
   for(let page=1;page<=doc.getNumberOfPages();page++){doc.setPage(page);doc.setFontSize(8);doc.setTextColor(95);doc.text(`Engineering estimate | Page ${page} of ${doc.getNumberOfPages()}`,15,289);}
   doc.save('pump-fan-affinity-report.pdf');setPDF('Report downloaded.');
  }catch(e){setPDF('Report export failed. Please try again.');}
 }
 return <section className={`af-app ${light?'af-light':''}`} ref={root} aria-label="Pump and fan affinity laws calculator"><div className="af-shell">
  <header className="af-heading"><div><p className="af-eyebrow">TILAK BHUSAL / ENGINEERING TOOLS</p><h1>Pump & fan<br/><em>affinity laws.</em></h1><div className="af-unit-switch" role="group" aria-label="Unit system"><button aria-pressed={!ip} onClick={()=>setIp(false)}>SI <small>{i.equipment==='fan'?'m³/h / Pa':'m³/h / m'}</small></button><button aria-pressed={ip} onClick={()=>setIp(true)}>Imperial <small>{i.equipment==='fan'?'cfm / in. w.g.':'US gpm / ft'}</small></button></div><p className="af-subtitle">Change the speed. Explore the curve. Understand the savings.</p></div><div className="af-actions"><button onClick={()=>{setLight(!light);try{localStorage.setItem('affinity-theme',light?'dark':'light');}catch{}}} aria-pressed={light}>{light?'☾ Dark mode':'☀ Light mode'}</button><button className="af-primary" disabled={!verified||!r||pdfState==='Preparing report…'} onClick={exportPDF}>↓ Export engineering PDF</button><span role="status">{pdfState}</span></div></header>
  <div className="af-layout"><aside className="af-panel af-inputs"><p className="af-eyebrow">01 / DEFINE YOUR MACHINE</p><div className="af-tabs">{['pump','fan'].map(v=><button key={v} aria-pressed={i.equipment===v} onClick={()=>switchEquipment(v)}>{v==='pump'?'◉ Pump':'✣ Fan'}</button>)}</div>
  <label className="af-field" htmlFor="af-mode"><span>Scaling model</span><select id="af-mode" value={i.mode} onChange={e=>update('mode',e.target.value)}><option value="speed">Speed / RPM</option>{i.equipment==='pump'&&<option value="trim">Impeller trim / same casing</option>}<option value="similarity">Geometric diameter scaling</option></select></label>
  <div className="af-fields">{['q','h','p','n1',...(i.mode==='speed'?['n2']:['d1','d2'])].map(field)}</div>
  <div className="af-divider"><label className="af-toggle"><input type="checkbox" checked={i.advanced} onChange={e=>update('advanced',e.target.checked)}/> Advanced mode <span>Custom exponents</span></label><div className="af-exponents">{['eq','eh','ep'].map((k,j)=><label key={k} htmlFor={`af-${k}`}>{['Flow','Head','Power'][j]}<input id={`af-${k}`} type="number" min="0.01" max="10" step="0.1" disabled={!i.advanced} value={i.advanced?i[k]:i.mode==='similarity'?[3,2,5][j]:[1,2,3][j]} onChange={e=>update(k,e.target.value===''?'':+e.target.value)}/></label>)}</div></div>
  <details open><summary>System curve & BEP</summary><div className="af-fields">{['shutoff','static','bep'].map(field)}</div><p className="af-note">A quadratic curve is fitted through baseline duty and shutoff. Enter manufacturer data for a useful estimate.</p></details>
  <details open><summary>Energy & operating schedule</summary><div className="af-fields">{['motor',...(i.mode==='speed'?['drive']:[]),'hours','rate'].map(field)}</div></details>
  {i.equipment==='pump'&&<details><summary>Cavitation screening</summary><div className="af-fields">{['npshr','npsha'].map(field)}</div><p className="af-note">NPSHa must represent proposed suction conditions. Speed-only NPSHr estimate; manufacturer margin still required.</p></details>}
  <button className="af-reset" onClick={()=>switchEquipment(i.equipment)}>Reset example</button></aside>
  <div className="af-main">{result.error&&<div className="af-warning" role="alert">{result.error}</div>}
  {r&&<div style={{visibility:verified?'visible':'hidden'}}><div className="af-results" aria-live="polite">{[['Flow',display('q',r.q),unit('q')],[i.equipment==='fan'?'Pressure':'Head',display('h',r.h),unit('h')],['Shaft power',display('p',r.p),unit('p')]].map(([name,v,u],j)=><article className="af-panel af-stat" key={name}><span>{name} <small>{['Q₂','H₂','P₂'][j]}</small></span><strong data-affinity-value={j}>{fmt(v)}</strong><p>{u} <span>{fmt((r.s[j]-1)*100)}%</span></p></article>)}</div><p className="af-note af-homologous">Affinity predictions at corresponding points · Q₂/Q₁ = r^{r.e[0]} · H₂/H₁ = r^{r.e[1]} · P₂/P₁ = r^{r.e[2]}</p>
  <section className="af-panel af-plot"><div className="af-section-heading"><div><p className="af-eyebrow">02 / EXPLORE THE DUTY POINT</p><h2>Performance meets demand</h2></div><span className="af-badge">{fmt(r.r*100)}% {i.mode==='speed'?'speed':'diameter'}</span></div><div className="af-legend"><span>┄ Baseline</span><span>━ Proposed</span><span>━ System</span><span>● Operating point</span></div><Curve i={i} r={r} svgRef={svg} ip={ip}/><div className="af-operating"><div><small>MODELED OPERATING FLOW</small><strong>{fmt(display('q',r.op))} <span>{unit('q')}</span></strong></div><div><small>OPERATING {i.equipment==='fan'?'PRESSURE':'HEAD'}</small><strong>{fmt(display('h',r.oh))} <span>{unit('h')}</span></strong></div><p>Intersection of the scaled machine curve and the unchanged system curve.</p></div></section>
  <div className="af-bottom"><section className="af-savings"><p className="af-eyebrow">03 / VFD & ENERGY ECONOMICS</p><h2>Estimated annual savings</h2><strong>{r.savings===null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(r.savings)}</strong><p>{fmt(r.kwh)} kWh/year · {fmt(i.hours)} operating hours</p><div className="af-costs"><span>Baseline input<b>{fmt(r.baseKW)} kW</b></span><span>Proposed input<b>{fmt(r.newKW)} kW</b></span></div><p className="af-note">Uses modeled operating flow and head with constant local hydraulic efficiency. Includes motor losses{ i.mode==='speed'?' and proposed VFD losses':''}. Negative savings indicate added cost.</p></section>
  <section className="af-panel af-motion"><div className="af-rotor-wrap"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="56" fill="none" stroke="currentColor" strokeDasharray="2 5"/><g style={{transformOrigin:'60px 60px',animation:`af-spin ${r.r>0?3/(i.mode==='speed'?r.r:1):3}s linear infinite`,animationPlayState:paused||(i.mode==='speed'&&r.r===0)?'paused':'running'}}>{Array.from({length:6},(_,j)=><path key={j} d="M60 55 C67 30 92 26 101 40 C94 49 77 60 63 64Z" transform={`rotate(${j*60} 60 60)`} fill="currentColor" opacity=".85"/>)}</g><circle cx="60" cy="60" r="10" fill="var(--af-bg)" stroke="currentColor" strokeWidth="3"/></svg></div><strong>{fmt(i.mode==='speed'?i.n2:i.n1)} <small>RPM</small></strong><p className="af-note">Illustrative rotation, scaled to speed</p><button aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Play animation':'Pause animation'}</button></section></div>
  {i.mode==='speed'&&<div className="af-panel af-slider"><label htmlFor="af-speed-slider">Explore speed <strong>{fmt(r.r*100)}% of baseline</strong></label><input id="af-speed-slider" aria-label="Proposed speed as percentage of baseline" type="range" min="0" max={Math.max(150,r.r*100)} step="1" value={r.r*100} onChange={e=>update('n2',i.n1*+e.target.value/100)}/><div><span>0%</span><span>75%</span><span>150%+</span></div></div>}
  <section className="af-panel af-screen"><h2>Engineering checks</h2>{r.warnings.length?r.warnings.map(w=><p className="af-warning" key={w}>{w}</p>):<p className="af-note">No screening thresholds exceeded. Confirm the actual operating envelope using manufacturer curves.</p>}<p className="af-note">BEP departure indicates a possible efficiency change; efficiency loss is not calculable from affinity laws alone. {r.nr!==null?`Approximate proposed NPSHr: ${value('npshr',r.nr)}; entered NPSHa: ${value('npsha',i.npsha)}. `:''}A positive NPSH difference alone does not establish an adequate margin.</p></section></div>}
  </div></div>
  <section className="af-method"><p className="af-eyebrow">THE ENGINEERING BEHIND THE NUMBERS</p><h2>One ratio. Three relationships.</h2><div className="af-lessons"><article><b>01 / Flow</b><h3>Q₂ = Q₁ × r</h3><p>At constant diameter, flow at a corresponding point varies directly with rotational speed.</p></article><article><b>02 / Head & pressure</b><h3>H₂ = H₁ × r²</h3><p>Head or pressure scales with the square of speed at constant fluid density.</p></article><article><b>03 / Shaft power</b><h3>P₂ = P₁ × r³</h3><p>At similar efficiency, shaft power follows the cube of speed. Electrical input also includes motor and drive losses.</p></article></div><details><summary>Model assumptions, diameter rules & references</summary><p>The baseline curve is H(Q) = H₀ − aQ², with a = (H₀ − H₁)/Q₁². The system curve is Hstatic + KQ², with K = (H₁ − Hstatic)/Q₁². Their proposed intersection is calculated analytically and checked with an independent numerical solver. These idealized curves cannot represent unstable or non-monotonic fan behavior.</p><p>Speed changes use 1/2/3 exponents. Same-casing pump trims approximately use 1/2/3. Geometrically similar machines use diameter exponents 3/2/5. Density stays constant. Manufacturer curves govern actual operation; custom calibration is only as reliable as its supporting measurements.</p><p>Operating shaft power is estimated as scaled shaft power × (operating flow / scaled flow) × (operating head / scaled head). This assumes constant local hydraulic efficiency. The savings estimate covers a single duty for the entered hours; actual savings need a duty profile and measured efficiencies.</p><p>References: <a href="https://wilo.com/us/en_us/Training/On-Demand-Resources/Pump-Basics/Affinity-Laws-Made-Simple/">Wilo affinity laws</a> · <a href="https://www.pumps.org/resources/pump-faqs/">Hydraulic Institute pump FAQs</a> · <a href="https://learning.amca.org/">AMCA fan engineering</a>.</p></details></section>
 <div className="af-export-bottom"><button className="af-primary" disabled={!verified||!r||pdfState==='Preparing report…'} onClick={exportPDF}>↓ Export engineering PDF</button><p role="status">{pdfState}</p></div>
 </div></section>;
}
