import React,{useState,useMemo,useRef,useEffect,useLayoutEffect} from 'react';
import {defaults,fields,units,display,internal,calculate,audit,notes,abmaReference} from '../lib/boiler-recovery.js';
import '../styles/affinity.css';
import '../styles/boiler-recovery.css';
const fmt=(v,d=2)=>v===null?'Unavailable':v.toLocaleString('en-US',{maximumFractionDigits:d});
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
function HeatFlow({r,system}){
 const data=[['Recovered flash',r.flashHeat,'#79ddd2',90],['Makeup preheat / HX',r.hx,'#edb661',190],['Drain / unused heat',r.unrecovered,'#90a9bf',290]];let offset=132;
 return <svg data-br-plot viewBox="0 0 760 360" role="img" aria-label="Blowdown heat balance split into recovered flash, makeup preheat, and drain or unused heat" className="br-svg"><title>Blowdown heat balance</title><desc>All heat rates are referenced to incoming makeup water. Recovered flash {fmt(r.flashHeat)} kW, makeup preheat {fmt(r.hx)} kW, losses {fmt(r.unrecovered)} kW.</desc>
 {data.map(([label,q,color,y])=>{const share=r.waste>0?q/r.waste:0,h=share*110,top=offset;offset+=h;return <g key={label}><path d={`M180 ${top} C300 ${top},340 ${y-h/2},465 ${y-h/2} L465 ${y+h/2} C340 ${y+h/2},300 ${top+h},180 ${top+h}Z`} fill={color} opacity=".25"/>{q>0&&<path className="br-flow" d={`M180 ${top+h/2} C300 ${top+h/2},340 ${y},465 ${y}`} stroke={color} strokeWidth="2" fill="none" strokeDasharray="5 12"/>}<rect x="465" y={y-30} width="268" height="66" rx="9" fill={color} opacity=".09"/><text x="482" y={y-7}>{label.toUpperCase()}</text><text className="br-svg-value" x="482" y={y+18}>{fmt(display(q,'heat',system),system==='IP'?0:2)} {units[system].heat} · {fmt(share*100,1)}%</text></g>;})}
 <rect x="25" y="128" width="155" height="118" rx="12" fill="#79ddd2" opacity=".12"/><text x="42" y="156">BLOWDOWN</text><text x="42" y="181">{fmt(display(r.waste,'heat',system),system==='IP'?0:2)}</text><text x="42" y="204">{units[system].heat} · 100%</text><text x="42" y="229">WASTE HEAT</text><text x="25" y="345">Thermal balance at the selected duty · Loss includes unused vapor and flash-condensate sensible heat</text></svg>;
}
function CashChart({r}){
 const vals=r.cashflow.flatMap(x=>[x.cash,x.discounted]),lo=Math.min(0,...vals),hi=Math.max(1,...vals),range=hi-lo;
 const x=n=>78+n*61,y=v=>258-(v-lo)/range*195,path=key=>r.cashflow.map((v,n)=>`${n?'L':'M'}${x(n)} ${y(v[key])}`).join(' ');
 return <svg data-br-plot viewBox="0 0 760 325" role="img" aria-label="Ten-year cumulative cash flow and discounted cash flow" className="br-svg"><title>10-year project cash flow</title><desc>Year zero installed cost and ten years of net fuel savings. Year ten cumulative cash {money(r.cashflow[10].cash)}, net present value {money(r.npv)}.</desc><text x="25" y="28">CUMULATIVE CASH FLOW / USD</text>{Array.from({length:5},(_,n)=>{const v=lo+n*range/4;return <g key={n}><path d={`M78 ${y(v)}H690`} stroke="#577185" opacity=".3"/><text x="67" y={y(v)+4} textAnchor="end">{fmt(v/1000,1)}k</text></g>;})}<path d={`M78 ${y(0)}H690`} stroke="#90a9bf" strokeDasharray="3 5"/>{r.cashflow.map(v=><g key={v.year}><text x={x(v.year)} y="282" textAnchor="middle">{v.year}</text><circle cx={x(v.year)} cy={y(v.cash)} r="3" fill="#79ddd2"/></g>)}<path d={path('cash')} fill="none" stroke="#79ddd2" strokeWidth="3" className="af-glow"/><path d={path('discounted')} fill="none" stroke="#edb661" strokeWidth="2" strokeDasharray="6 5"/><text x="78" y="311">Green: cash · Gold: discounted cash · Horizontal axis: year</text></svg>;
}
export default function BoilerRecoveryCalculator(){
 const [i,setI]=useState(defaults),[system,setSystem]=useState('IP'),[light,setLight]=useState(false),[advanced,setAdvanced]=useState(false),[status,setStatus]=useState(''),[verified,setVerified]=useState(false),root=useRef(null);
 const result=useMemo(()=>{try{const r=calculate(i);if(audit(i,r)<8)throw Error('Results could not be verified. Check the inputs before continuing.');return {r};}catch(e){return {error:e.message};}},[i]);const r=result.r;
 useEffect(()=>{try{setLight(localStorage.getItem('boiler-recovery-theme')==='light');}catch{}},[]);
 const results=r?[
 ['blow','Required blowdown','flow',r.blow],['fraction','Flash fraction','%',r.flashFraction*100],['recovered','Useful heat recovered','heat',r.recovered],
 ['flash','Recovered flash latent heat','heat',r.flashHeat],['hx','Liquid-liquid HX duty','heat',r.hx],['loss','Drain / unused heat','heat',r.unrecovered],
 ['area','Required liquid-liquid HX area','area',r.area],['makeup','Required fresh makeup','flow',r.makeup],['outlet','Final heated makeup','temp',r.makeupOut]
 ]:[];
 useLayoutEffect(()=>{setVerified(false);if(!r)return;const nodes=[...root.current.querySelectorAll('[data-br-result]')];const expected=new Map(results.map(([key,,kind,value])=>[key,display(value,kind,system)]));const ok=nodes.length===results.length&&nodes.every(n=>Math.abs(Number(n.textContent.replaceAll(',',''))-expected.get(n.dataset.brResult))<=.000501);setVerified(ok&&audit(i,r)>=8);},[r,system,i]);
 function update(k,v){setVerified(false);setI(old=>({...old,[k]:v}));setStatus('');}
 function field(k){const [label,kind]=fields[k],unit=units[system][kind]??kind;return <label key={k} className="af-field" htmlFor={`br-${k}`}><span>{label}<small>{unit}</small></span><input id={`br-${k}`} type="number" step="any" value={i[k]===''?'':Number(display(i[k],kind,system).toFixed(6))} onChange={e=>update(k,e.target.value===''?'':internal(Number(e.target.value),kind,system))}/></label>;}
 const row=([key,label,kind,value])=><div key={key}><dt>{label}</dt><dd><strong data-br-result={key}>{fmt(display(value,kind,system),3)}</strong> <span>{units[system][kind]??kind}</span></dd></div>;
 async function exportPDF(){if(!r||!verified||status==='Preparing report…')return;const snapshot={i:{...i},r,system,notes,plots:[...root.current.querySelectorAll('[data-br-plot]')].map(n=>n.cloneNode(true)),inputs:Object.entries(fields).map(([k,[label,kind]])=>[label,`${fmt(display(i[k],kind,system),4)} ${units[system][kind]??kind}`])};setStatus('Preparing report…');try{const {exportBoilerReport}=await import('../lib/boiler-recovery-report.js');await exportBoilerReport(snapshot);setStatus('Report downloaded.');}catch{setStatus('Report export failed. Please try again.');}}
 const exportButton=<button className="af-primary" disabled={!r||!verified||status==='Preparing report…'} onClick={exportPDF}>↓ Export engineering PDF</button>;
 return <section className={`af-app br-app ${light?'af-light':''}`} ref={root} aria-label="Boiler blowdown heat recovery calculator"><div className="af-shell">
 <header className="af-heading"><div><p className="af-eyebrow">TILAK BHUSAL / ENGINEERING TOOLS</p><h1>Boiler blowdown.<br/><em>Recover the heat.</em></h1><div className="af-unit-switch" role="group" aria-label="Unit system">{[['SI','kg/h · bar · °C'],['IP','lb/h · psi · °F']].map(([key,label])=><button key={key} aria-pressed={system===key} onClick={()=>{setVerified(false);setSystem(key);}}>{key==='IP'?'Imperial':'SI'}<small>{label}</small></button>)}</div><p className="af-subtitle">Size the recovery. Follow the heat. Make the business case.</p></div><div className="af-actions"><button aria-pressed={light} onClick={()=>{setLight(!light);try{localStorage.setItem('boiler-recovery-theme',light?'dark':'light');}catch{}}}>{light?'☾ Dark mode':'☀ Light mode'}</button>{exportButton}<span role="status">{status}</span></div></header>
 <div className="af-layout"><aside className="af-panel af-inputs"><p className="af-eyebrow">01 / WATER & STEAM BALANCE</p><h2>Boiler conditions</h2><div className="af-fields">{['steam','tds','limit','return','boiler','flash'].map(field)}</div><p className="af-note">TDS is measured in treated makeup, before mixing with clean returned condensate. Both pressures are gauge.</p><p className="af-note">Historical ABMA reference at this pressure: {Number.isFinite(i.boiler)?fmt(abmaReference(i.boiler),0):'—'} ppm boiler TDS, as reported by the National Board in 1999. Use the manufacturer-approved limit.</p>
 <details open><summary>Heat recovery design</summary><div className="af-fields">{['cold','drain','maxMakeup'].map(field)}</div><p className="af-note">Makeup passes through the liquid-liquid HX, then an indirect flash condenser. No flash-condensate water return is assumed.</p></details>
 <div className="af-divider"><label className="af-toggle"><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/>Advanced mode<span>Heat transfer & availability</span></label>{advanced?<div className="af-fields">{['U','use'].map(field)}</div>:<p className="af-note">Fouled U = {fmt(display(i.U,'u',system))} {units[system].u}; flash capture = {fmt(i.use)}%. Enable advanced mode to adjust.</p>}</div>
 <details open><summary>Fuel & project economics</summary><div className="af-fields">{['fuel','efficiency','hours','capital'].map(field)}</div></details><details><summary>Operating costs & cash flow</summary><div className="af-fields">{['maintenance','pump','electric','escalation','discount'].map(field)}</div></details><button className="af-reset" onClick={()=>{setVerified(false);setI({...defaults});setStatus('');}}>Reset example</button></aside>
 <div className="af-main">{result.error&&<p role="alert" className="af-warning">{result.error}</p>}{r&&<div style={{visibility:verified?'visible':'hidden'}}>
 <div className="af-results" aria-live="polite">{results.slice(0,3).map(([key,label,kind,value])=><article key={key} className="af-panel af-stat"><span>{label}</span><strong data-br-result={key}>{fmt(display(value,kind,system),3)}</strong><p>{units[system][kind]??kind}</p></article>)}</div>
 <p className="af-note af-homologous">Blowdown = {fmt(r.blowPercent)}% of makeup · {fmt(r.feedPercent)}% of total feedwater · Saturated boiler water {fmt(display(r.b.t,'temp',system))}{units[system].temp}</p>
 <section className="af-panel"><div className="af-section-heading"><div><p className="af-eyebrow">02 / TWO-STAGE HEAT RECOVERY</p><h2>Every unit of heat, accounted for.</h2></div><span className="af-badge">{fmt(r.waste?100*r.recovered/r.waste:0,1)}% useful recovery</span></div><HeatFlow r={r} system={system}/><dl className="br-metrics">{results.slice(3,6).map(row)}</dl><p className="af-note br-pad">Flash recovery credits latent heat only. The loss branch includes residual liquid, unused vapor and flash-condensate sensible heat, all above the makeup inlet reference.</p></section>
 <div className="br-economics"><section className="af-savings"><p className="af-eyebrow">03 / THE BUSINESS CASE</p><h2>Avoided fuel costs</h2><strong>{money(r.fuelSavings)}<small> / year</small></strong><p>Estimated gross fuel savings at the entered operating duty</p><div className="af-costs"><span>Fuel avoided<b>{fmt(r.fuelMMBtu)} MMBtu/yr</b></span><span>Net annual savings<b>{money(r.net)}</b></span></div><p className="af-note">Includes both recovery stages. Maintenance and auxiliary electricity are deducted from net savings.</p></section><section className="af-panel br-payback"><p className="af-eyebrow">PROJECT RETURN</p><h2>{r.payback===null?'No positive payback':`${fmt(r.payback)} years`}</h2><p className="af-note">Simple payback · year-one net savings</p><dl><div><dt>Annual return on cost</dt><dd>{r.roi===null?'Unavailable':`${fmt(r.roi,1)}%`}</dd></div><div><dt>10-year NPV</dt><dd>{money(r.npv)}</dd></div><div><dt>Annual operating costs</dt><dd>{money(r.auxiliary+i.maintenance)}</dd></div></dl></section></div>
 <section className="af-panel br-panel"><div className="af-section-heading"><div><p className="af-eyebrow">04 / EQUIPMENT DUTY</p><h2>Start with the thermal requirements.</h2></div></div><dl className="br-metrics">{results.slice(6).map(row)}</dl><dl className="br-metrics br-secondary">{[
 ['Flash vapor generated',`${fmt(display(r.flashMass,'flow',system))} ${units[system].flow}`],['Flash vapor volume',`${fmt(display(r.vaporVolume,'volume',system))} ${units[system].volume}`],['Residual liquid to HX',`${fmt(display(r.residual,'flow',system))} ${units[system].flow}`],['Vapor-only diameter screen',`${fmt(r.separatorDiameter*(system==='SI'?1000:39.37007874))} ${system==='SI'?'mm':'in'}`],['Makeup leaving liquid HX',`${fmt(display(r.hxOut,'temp',system))} ${units[system].temp}`],['HX effectiveness / NTU',`${fmt(r.effectiveness*100)}% / ${fmt(r.ntu,3)}`]
 ].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="af-note br-pad">One shell pass / two tube passes. Area excludes the flash condenser. The 3 m/s vapor-velocity diameter is a preliminary screen; vessel hold-up, internals, nozzles and pressure ratings still require manufacturer sizing. Maintain flash pressure through the residual-liquid exchanger.</p></section>
 <section className="af-panel br-panel"><div className="af-section-heading"><div><p className="af-eyebrow">05 / TEN-YEAR OUTLOOK</p><h2>From installed cost to recovered value.</h2></div></div><CashChart r={r}/><details className="br-cash-table"><summary>View annual cash flow table</summary><div className="br-table-wrap"><table><caption>Cumulative project cash flow (USD)</caption><thead><tr><th scope="col">Year</th><th scope="col">Cash</th><th scope="col">Discounted cash</th></tr></thead><tbody>{r.cashflow.map(c=><tr key={c.year}><th scope="row">{c.year}</th><td>{money(c.cash)}</td><td>{money(c.discounted)}</td></tr>)}</tbody></table></div></details></section>
 <section className="af-panel af-screen"><h2>Design checks</h2>{r.warnings.map(w=><p className="af-warning" key={w}>{w}</p>)}{!r.warnings.length&&<p className="af-note">No screening thresholds exceeded for this scenario. Confirm water chemistry, coincident load and equipment duties before selection.</p>}<p className="af-note">Thermal/economic estimate. Pressure-vessel construction, relief protection, control sequencing and final mechanical design are outside this tool.</p></section>
 </div>}</div></div>
 <section className="af-method"><p className="af-eyebrow">THE THERMODYNAMICS BEHIND THE NUMBERS</p><h2>Control the solids. Recover the energy.</h2><div className="af-lessons"><article><b>01 / Blowdown mass balance</b><h3>B / M = Cm / Cb</h3><p>Makeup solids leave in blowdown. Clean condensate return reduces fresh makeup and required continuous blowdown.</p></article><article><b>02 / Flash separation</b><h3>x = Δhf / hfg</h3><p>The pressure drop converts part of the hot liquid into steam. Recovery depends on a simultaneous heat sink.</p></article><article><b>03 / Heat exchanger sizing</b><h3>A = NTU × Cmin / U</h3><p>A one-shell-pass thermal model relates the selected drain temperature to required fouled heat-transfer area.</p></article></div><details><summary>Calculation basis, ABMA TDS limits & references</summary>{notes.map(n=><p key={n}>{n}</p>)}<p>References: <a href="https://www.nationalboard.org/PrintPage.aspx?pageID=244">National Board: historical ABMA water limits</a> · <a href="https://www.energy.gov/sites/prod/files/2014/05/f16/steam9_blowdown.pdf">DOE Steam Tip Sheet 9</a> · <a href="https://www.spiraxsarco.com/learn-about-steam/the-boiler-house/heat-recovery-from-boiler-blowdown-tds-control-only">Spirax Sarco heat recovery guidance</a> · <a href="https://iapws.org/technical-guidance/release/IF97-Rev">IAPWS-IF97 properties</a> · <a href="https://fchart.com/ees/heat_transfer_library/heat_exchangers/hs1000.htm">F-Chart effectiveness–NTU model</a>.</p></details></section><div className="af-export-bottom">{exportButton}<p role="status">{status}</p></div>
 </div></section>;
}
