import React,{useState,useMemo,useRef,useEffect,useLayoutEffect} from 'react';
import {defaults,fields,calculate,audit} from '../lib/power-factor.js';
import '../styles/affinity.css';
import '../styles/power-factor.css';
const f=(v,d=2)=>v===null?'Unavailable':v.toLocaleString('en-US',{maximumFractionDigits:d});
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const tariffs={kva:'kVA demand billing',penalty:'PF-adjusted kW demand',switch:'Hypothetical switch to kW tariff',kw:'kW demand / no PF penalty'};
function Triangle({i,r}){
 const [q,setQ]=useState(r.q2),current=useRef(r.q2);
 useEffect(()=>{
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){current.current=r.q2;setQ(r.q2);return;}
  let id,start=null;const from=current.current;
  const animate=t=>{start??=t;const progress=Math.min(1,(t-start)/280);current.current=from+(r.q2-from)*(1-(1-progress)**3);setQ(current.current);if(progress<1)id=requestAnimationFrame(animate);};
  id=requestAnimationFrame(animate);return()=>cancelAnimationFrame(id);
 },[r.q2]);
 const height=245,scale=Math.min(570/i.kw,height/Math.max(1,r.q1)),x0=88,y0=335,x1=x0+i.kw*scale,y1=y0-r.q1*scale,y2=y0-q*scale;
 const angle=Math.atan2(q,i.kw),radius=75,arcX=x0+radius*Math.cos(angle),arcY=y0-radius*Math.sin(angle);
 return <svg data-pf-plot viewBox="0 0 800 410" role="img" aria-label="Fundamental power triangle before and after correction" className="pf-svg">
  <title>Fundamental power triangle</title><desc>Active power {f(i.kw)} kW. Reactive power reduces from {f(r.q1)} to {f(r.q2)} kVAR. Phase angle reduces from {f(r.theta1)} to {f(r.theta2)} degrees. Harmonic apparent power is shown separately in the results.</desc>
  {Array.from({length:9},(_,n)=><path key={n} d={`M${70+n*80} 55V355M70 ${55+n*37.5}H725`} className="pf-grid"/>)}
  <path d={`M${x0} ${y0}L${x1} ${y1}V${y0}Z`} stroke="#90a9bf" strokeDasharray="7 6" strokeWidth="2" fill="none"/>
  <path d={`M${x0} ${y0}L${x1} ${y2}V${y0}Z`} fill="#49c9d518" stroke="#49c9d5" strokeWidth="3" className="af-glow"/>
  <path d={`M${x0} ${y0}H${x1}`} stroke="#7edab9" strokeWidth="4"/>
  <path d={`M${x1} ${y0}V${y2}`} stroke="#edb661" strokeWidth="4"/>
  {angle>0&&<path d={`M${x0+radius} ${y0}A${radius} ${radius} 0 0 0 ${arcX} ${arcY}`} stroke="#c0a5ef" fill="none" strokeWidth="2"/>}
  <circle cx={x1} cy={y2} r="6" fill="#7edab9" stroke="#fff" strokeWidth="2"/>
  <text x="82" y="33">FUNDAMENTAL / DISPLACEMENT TRIANGLE</text>
  <text x={(x0+x1)/2} y={y0+35} textAnchor="middle">{f(i.kw)} kW · ACTIVE POWER</text>
  <text x={Math.min(730,x1+14)} y={Math.max(55,(y0+y2)/2)}>{f(q)} kVAR</text>
  <text x={(x0+x1)/2} y={(y0+y2)/2-15} textAnchor="middle">{f(Math.hypot(i.kw,q))} kVA fundamental</text>
  <text x={x0+90} y={y0-12}>θ = {f(angle*180/Math.PI)}°</text>
  <text x="82" y="395">Dashed: existing · Cyan: corrected · Harmonics are outside this 2D triangle</text>
 </svg>;
}
function BillChart({i,r}){
 const max=Math.max(r.bill1,r.bill2,1)*1.12,scale=480/max;
 return <svg data-pf-plot viewBox="0 0 740 245" role="img" aria-label="Monthly utility bill before versus after correction" className="pf-svg"><title>Monthly utility bill estimate</title>
  <text x="25" y="28">MONTHLY UTILITY BILL / USD</text>
  {[['Before',r.demand1,r.energy1,r.bill1],['After',r.demand2,r.energy2,r.bill2]].map(([label,demand,energy,total],j)=><g key={label}><text x="25" y={88+j*75}>{label}</text><rect x="105" y={60+j*75} width={demand*scale} height="40" fill="#49c9d5"/><rect x={105+demand*scale} y={60+j*75} width={energy*scale} height="40" fill="#7edab9"/><rect x={105+(demand+energy)*scale} y={60+j*75} width={i.fixed*scale} height="40" fill="#90a9bf"/><text x={115+total*scale} y={86+j*75}>{money(total)}</text></g>)}
  <text x="105" y="223">Cyan: demand · Green: load + feeder/device energy · Gray: fixed charges</text></svg>;
}
function CapacityChart({i,r}){
 const max=Math.max(i.transformer,r.peakS1,r.peakS2)*1.12,scale=480/max;
 return <svg data-pf-plot viewBox="0 0 740 245" role="img" aria-label="Transformer capacity used and available before and after" className="pf-svg"><title>Transformer peak capacity</title><text x="25" y="28">TRANSFORMER CAPACITY / kVA</text>
  {[['Before',r.peakS1],['After',r.peakS2]].map(([label,s],j)=><g key={label}><text x="25" y={88+j*75}>{label}</text><rect x="105" y={60+j*75} width={i.transformer*scale} height="40" fill="#7edab955"/><rect x="105" y={60+j*75} width={Math.min(s,i.transformer)*scale} height="40" fill="#49c9d5"/>{s>i.transformer&&<rect x={105+i.transformer*scale} y={60+j*75} width={(s-i.transformer)*scale} height="40" fill="#ed9968"/>}<text x={115+Math.max(s,i.transformer)*scale} y={86+j*75}>{f(s/i.transformer*100,1)}%</text></g>)}
  <path d={`M${105+i.transformer*scale} 52V184`} stroke="#edb661" strokeDasharray="4 3"/><text x="105" y="223">Cyan: used · Green: available · Orange: overload · Dashed: nameplate</text></svg>;
}
const notes=[
 'Balanced three-phase load, fixed sinusoidal line voltage, lagging displacement PF and constant active load are assumed. This is an engineering estimate, not a stamped design or an IEEE 519 / NEC compliance assessment.',
 'Capacitor compensation Qc = P[tan(acos(PF1)) - tan(acos(PF2))]. The peak-duty bank is scaled by peak kW / operating kW; it requires automatic steps at lower load. kVAR is reactive-power rating, not capacitance in microfarads.',
 'Advanced mode uses true PF = displacement PF / sqrt(1 + THDi^2) for the initial state. After correction, harmonic amperes remain constant unless the AHF scenario is enabled. Residual THDi is referenced to the corrected fundamental current.',
 'AHF sizing assumes proportional reduction of the harmonic spectrum and simultaneous worst-case peak load. The allowance is user-selected, not a code requirement. The AHF is allocated to harmonic filtering; fundamental VARs are supplied by the capacitor bank. Confirm spectra, neutral current, phase imbalance, voltage, duty and manufacturer derating.',
 'IEEE 519 evaluates harmonic performance at the point of common coupling using voltage distortion, individual harmonic limits and current TDD with system short-circuit information. THDi alone cannot demonstrate compliance. NEC requirements for installation, ratings and protection require a separate design review.',
 'Feeder losses = 3 I_RMS^2 R. R is the operating-temperature resistance of one phase in only the corrected, customer-metered upstream segment. Harmonic-frequency resistance changes, neutral current, transformer core/eddy losses and voltage drop are excluded. Banks at the service entrance do not reduce losses in downstream uncorrected feeders.',
 'Operating kW is downstream useful load; modeled feeder losses are added once to the energy bill. Demand uses the separately entered peak and selected meter PF basis. The same peak/PF and rates repeat for 12 months, with no demand ratchet or minimum billing demand. Demand effects of feeder and correction-device active losses are excluded.',
 'Monthly bill includes modeled demand, load energy, feeder losses, correction-device energy and entered fixed charges; taxes and unentered charges are excluded. Annual net savings subtract device energy and added maintenance. Simple payback and annual return exclude financing, incentives and time value of money.',
 'Released kVA is the arithmetic peak apparent-load reduction, not an authorization to add load. Transformer harmonic derating, ambient temperature, cooling and protection may constrain usable capacity. Resonance order uses transformer impedance only and an infinite upstream source; use a complete harmonic study for selection.'
];
export default function PowerFactorCalculator(){
 const [i,setI]=useState(defaults),[light,setLight]=useState(false),[verified,setVerified]=useState(false),[status,setStatus]=useState(''),root=useRef(null);
 const result=useMemo(()=>{try{const r=calculate(i);if(audit(i,r)<8)throw Error('Calculation verification failed. Please check inputs.');return {r};}catch(e){return {error:e.message};}},[i]);const r=result.r;
 useEffect(()=>{try{setLight(localStorage.getItem('power-factor-theme')==='light');}catch{}},[]);
 useLayoutEffect(()=>{setVerified(false);if(!r)return;const nodes=[...root.current.querySelectorAll('[data-pf-result]')];const ok=nodes.length===7&&nodes.every(n=>{const expected=r[n.dataset.pfResult];const shown=Number(n.textContent.replaceAll(',',''));return Number.isFinite(shown)&&Math.abs(shown-expected)<=.000051;});setVerified(ok&&audit(i,r)>=8);},[r,i]);
 const update=(k,v)=>{setVerified(false);setI(old=>({...old,[k]:v}));};
 const field=k=><label className="af-field" key={k} htmlFor={`pf-${k}`}><span>{fields[k][0]} <small>{fields[k][1]}</small></span><input id={`pf-${k}`} type="number" step={['pf','target','threshold'].includes(k)?'.01':'any'} value={i[k]} onChange={e=>update(k,e.target.value===''?'':Number(e.target.value))}/></label>;
 async function exportPDF(){
  if(!r||!verified||status==='Preparing report…')return;
  const charts=[...root.current.querySelectorAll('[data-pf-plot]')].map(el=>el.cloneNode(true));
  // The power triangle may still be interpolating visually; reports always use the exact final state.
  charts[0]=null;
  const activeKeys=Object.keys(fields).filter(k=>i.advanced||!['thdi','residual','margin','impedance'].includes(k));
  const snapshot={i:{...i},r:{...r},charts,notes,inputs:activeKeys.map(k=>[fields[k][0],`${f(i[k],4)} ${fields[k][1].replace('Ω','ohm').replace('I₁','I1')}`]),tariff:tariffs[i.tariff]};
  setStatus('Preparing report…');try{const {exportPowerFactorReport}=await import('../lib/power-factor-report.js');await exportPowerFactorReport(snapshot);setStatus('Report downloaded.');}catch{setStatus('Report export failed. Please try again.');}
 }
 const exportButton=<button className="af-primary" disabled={!r||!verified||status==='Preparing report…'} onClick={exportPDF}>↓ Export engineering PDF</button>;
 return <section className={`af-app pf-app ${light?'af-light':''}`} ref={root} aria-label="Power factor correction calculator"><div className="af-shell">
 <header className="af-heading"><div><p className="af-eyebrow">TILAK BHUSAL / ENGINEERING TOOLS</p><h1>Power factor.<br/><em>Real savings.</em></h1><p className="af-subtitle">Size compensation. Recover capacity. Understand your demand bill.</p><p className="pf-unit-note">ELECTRICAL UNITS · kW / kVA / kVAR · Balanced three-phase</p></div><div className="af-actions"><button aria-pressed={light} onClick={()=>{setLight(!light);try{localStorage.setItem('power-factor-theme',light?'dark':'light');}catch{}}}>{light?'☾ Dark mode':'☀ Light mode'}</button>{exportButton}<span role="status">{status}</span></div></header>
 <div className="af-layout"><aside className="af-panel af-inputs"><p className="af-eyebrow">01 / DEFINE THE ELECTRICAL LOAD</p><h2>Facility conditions</h2><div className="af-fields">{['kw','peak','pf','target','voltage','transformer'].map(field)}</div><p className="af-note">Existing and target PF are lagging displacement factors. Peak demand uses the same PF and load composition. Enter downstream load kW; feeder losses are modeled separately.</p>
 <div className="af-divider"><label className="af-toggle"><input type="checkbox" checked={i.advanced} onChange={e=>update('advanced',e.target.checked)}/> Advanced mode <span>Harmonics & AHF</span></label>{i.advanced&&<><div className="af-fields">{['thdi','impedance'].map(field)}</div><label className="af-toggle pf-check"><input type="checkbox" checked={i.filter} onChange={e=>update('filter',e.target.checked)}/> Include active harmonic filter</label>{i.filter&&<div className="af-fields">{['residual','margin'].map(field)}</div>}<p className="af-note">THDi is relative to fundamental current. Voltage distortion and harmonic phase spectra are not modeled.</p></>}</div>
 <details open><summary>Utility tariff & billing</summary><label className="af-field" htmlFor="pf-tariff"><span>Billing model</span><select id="pf-tariff" value={i.tariff} onChange={e=>update('tariff',e.target.value)}>{Object.entries(tariffs).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="af-field" htmlFor="pf-basis"><span>Utility meter PF basis</span><select id="pf-basis" value={i.basis} onChange={e=>update('basis',e.target.value)}><option value="true">True (total) power factor</option><option value="displacement">Displacement power factor</option></select></label><div className="af-fields">{[...(['kva','switch'].includes(i.tariff)?['kvaRate']:[]),...(['penalty','switch','kw'].includes(i.tariff)?['kwRate']:[]),...(i.tariff==='penalty'?['threshold']:[]),'energyRate','fixed'].map(field)}</div><p className="af-note">PF-adjusted demand = peak kW × max(1, threshold / meter PF). Confirm this formula and meter basis against your actual tariff.</p></details>
 <details><summary>Feeder losses & annual economics</summary><div className="af-fields">{['resistance','hours','deviceLoss','capital','maintenance'].map(field)}</div><p className="af-note">Only the corrected upstream, metered circuit segment benefits. Enter resistance per phase at operating temperature. Include all bank/filter losses and installation costs.</p></details><button className="af-reset" onClick={()=>{setVerified(false);setI({...defaults});}}>Reset example</button></aside>
 <div className="af-main">{result.error&&<p className="af-warning" role="alert">{result.error}</p>}{r&&<div style={{visibility:verified?'visible':'hidden'}}>
 <div className="af-results" aria-live="polite">{[['bank','Compensation at peak','kVAR'],['s1','Existing apparent power','kVA'],['s2','Corrected apparent power','kVA']].map(([key,label,u])=><article className="af-panel af-stat" key={key}><span>{label}</span><strong data-pf-result={key}>{f(r[key],4)}</strong><p>{u}</p></article>)}</div>
 <p className="af-note af-homologous">Capacitor bank sized at {f(i.peak)} kW peak · kVA cards use {f(i.kw)} kW operating duty · {i.advanced?'Includes modeled harmonic current':'Sinusoidal-current model'}</p>
 <section className="af-panel"><div className="af-section-heading"><div><p className="af-eyebrow">02 / EXPLORE THE POWER TRIANGLE</p><h2>Less reactive. More productive.</h2></div><span className="af-badge">{f(i.pf,3)} → {f(i.target,3)} displacement PF</span></div><Triangle i={i} r={r}/><div className="pf-triangle-data">{[['q1','Existing kVAR'],['q2','Proposed kVAR'],['theta1','Existing angle (°)'],['theta2','Proposed angle (°)']].map(([key,label])=><div key={key}><small>{label}</small><strong data-pf-result={key}>{f(r[key],4)}</strong></div>)}</div><div className="af-slider"><label htmlFor="pf-slider">Explore target displacement PF <strong>{f(i.target,3)}</strong></label><input id="pf-slider" type="range" min={i.pf} max="1" step=".001" value={i.target} onChange={e=>update('target',+e.target.value)}/><div><span>{f(i.pf,3)}</span><span>Unity · 1.000</span></div></div></section>
 <div className="pf-economics"><section className="af-savings"><p className="af-eyebrow">03 / UTILITY DEMAND OPTIMIZATION</p><h2>Avoided annual surcharges</h2><strong>{money(r.demandSavings)}</strong><p>Modeled demand-charge reduction · {tariffs[i.tariff]}</p><div className="af-costs"><span>Monthly demand before<b>{money(r.demand1)}</b></span><span>Monthly demand after<b>{money(r.demand2)}</b></span></div><p className="af-note">12 identical peak-demand months. Tariff-specific rules, ratchets and minimums may change the result.</p></section><section className="af-panel pf-net"><p className="af-eyebrow">PROJECT ECONOMICS</p><h2>{money(r.net)} <small>/ year net</small></h2><dl><div><dt>Simple payback</dt><dd>{r.payback===null?'Unavailable':`${f(r.payback)} years`}</dd></div><div><dt>Annual return on cost</dt><dd>{r.roi===null?'Unavailable':`${f(r.roi,1)}%`}</dd></div><div><dt>Feeder loss savings</dt><dd>{money(r.lossSavings)}/yr</dd></div><div><dt>Device energy + maintenance</dt><dd>{money(r.deviceCost+i.maintenance)}/yr</dd></div></dl></section></div>
 <section className="af-panel pf-charts"><BillChart i={i} r={r}/><CapacityChart i={i} r={r}/><div className="pf-triangle-data"><div><small>Peak capacity liberated</small><strong>{f(r.freed)} <span>kVA</span></strong></div><div><small>Corrected spare capacity</small><strong>{f(Math.max(0,i.transformer-r.peakS2))} <span>kVA</span></strong></div><div><small>Feeder I²R reduction</small><strong>{f(r.lossReduction*100)} <span>%</span></strong></div><div><small>Feeder energy saved</small><strong>{f(r.lossKWh,0)} <span>kWh/yr</span></strong></div></div></section>
 {i.advanced&&<section className="af-panel pf-detail"><p className="af-eyebrow">04 / HARMONIC CURRENT MODEL</p><h2>Displacement is only part of the story.</h2><div className="pf-triangle-data"><div><small>True PF before → after</small><strong>{f(r.true1,4)} → {f(r.true2,4)}</strong></div><div><small>Proposed current THDi</small><strong>{f(r.postTHDi)}%</strong></div><div><small>Peak harmonic cancellation</small><strong>{f(r.filterAmps)} A</strong></div><div><small>AHF screening rating / phase</small><strong>{i.filter?`${f(r.filterSize)} A`:'Not included'}</strong></div></div><p className="af-note">AHF rating includes the entered allowance and harmonic compensation only. Capacitors supply the fundamental VAR correction. Final filter selection needs measured harmonic spectra and manufacturer review; THDi is not IEEE 519 TDD.</p></section>}
 <section className="af-panel af-screen"><h2>System checks & design boundaries</h2>{r.warnings.map(w=><p className="af-warning" key={w}>{w}</p>)}{!r.warnings.length&&<p className="af-note">No modeled screening thresholds exceeded. Verify the tariff, load profile, harmonic spectrum and equipment operating limits.</p>}<p className="af-note">{!i.advanced?'Harmonics are not evaluated in standard mode. ':''}Capacitor ratings, switching steps, protection and conductor sizing require a separate electrical design.</p></section>
 </div>}</div></div>
 <section className="af-method"><p className="af-eyebrow">THE ELECTRICAL ENGINEERING BEHIND THE NUMBERS</p><h2>Correct the load. Check the whole system.</h2><div className="af-lessons"><article><b>01 / Reactive compensation</b><h3>Qc = P(tan θ₁ − tan θ₂)</h3><p>Correct the lagging fundamental reactive demand. Automatic steps match the bank to the changing load.</p></article><article><b>02 / True power factor</b><h3>PF = P / S</h3><p>Harmonic current adds RMS loading without useful active power in this sinusoidal-voltage model. A capacitor does not remove it.</p></article><article><b>03 / Distribution losses</b><h3>Ploss = 3I²R</h3><p>Lower upstream current reduces resistive losses in the corrected segment. Active load energy is otherwise unchanged.</p></article></div><details><summary>Calculation basis, tariff formulas & references</summary>{notes.map(n=><p key={n}>{n}</p>)}<p>Sources: <a href="https://www.eaton.com/content/dam/eaton/products/low-voltage-power-distribution-controls-systems/power-factor-corrections/portfolio/eaton-pfc-guide-plant-engineer-SA02607001E.pdf">Eaton plant-engineer PF guide</a> · <a href="https://www.eaton.com/content/dam/eaton/products/low-voltage-power-distribution-controls-systems/power-factor-corrections/power-factor-correction-harmonic-resonance-white-paper-IA02607001E.PDF">Eaton harmonic resonance guidance</a>. Harmonic compliance and installation requirements must be checked against the applicable IEEE 519 and NEC editions.</p></details></section>
 <div className="af-export-bottom">{exportButton}<p role="status">{status}</p></div>
 </div></section>;
}
